[pytest]
addopts = -s --cov=. --cov-report=html -p no:warnings --ignore=*/migrations/* --log-disable=django.db.backends --create-db --reuse-db
DJANGO_SETTINGS_MODULE = {{ project_name }}.settings.pytest
