# Generated by Django 6.0.3 on 2026-05-13 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='action_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='notification',
            name='action_type',
            field=models.CharField(blank=True, choices=[('none', 'No Action'), ('open_url', 'Open URL'), ('open_form', 'Open Form'), ('rate_app', 'Rate App'), ('rate_exam', 'Rate Exam'), ('view_exam', 'View Exam')], default='none', max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('wallet', 'Wallet'), ('chat', 'Chat'), ('system', 'System'), ('survey', 'Survey'), ('announcement', 'Announcement')], default='system', max_length=20),
        ),
    ]
