# Generated by Django 6.0.3 on 2026-05-13 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_add_action_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='action_type',
            field=models.CharField(blank=True, choices=[('none', 'No Action'), ('rate_app', 'Rate App')], default='none', max_length=50),
        ),
    ]
