# Generated by Django 6.0.3 on 2026-04-17 10:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examattempt',
            name='accumulated_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='last_resumed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='examattempt',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('paused', 'Paused'), ('submitted', 'Submitted'), ('expired', 'Expired')], default='in_progress', max_length=20),
        ),
    ]
