# Generated by Django 6.0.3 on 2026-04-17 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_examattempt_accumulated_seconds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attemptanswer',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
    ]
