upstream django_app {
    server be:8000;
}

server {
    listen 80;

    # request timed out -- default 60
    client_body_timeout 600;
    client_header_timeout 600;

    # if client stop responding, free up memory -- default 60
    send_timeout 600;

    # server will close connection after this time -- default 75
    keepalive_timeout 600;

    location /static/ {
        alias /BE/static/;
        add_header Cache-Control "max-age=2629746, public";
    }

    location /media/ {
        alias /BE/media/;
        add_header Cache-Control "max-age=2629746, public";
        add_header 'Access-Control-Allow-Origin' '*';
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
        add_header 'Access-Control-Allow-Headers' 'User-Agent,Keep-Alive,Content-Type';
        add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range';
    }

    location ~ ^/(admin|ckeditor) {
        proxy_pass http://django_app;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        auth_basic "Administrator’s Area";
        auth_basic_user_file /etc/nginx/.htpasswd;
    }

    location / {
        proxy_pass http://django_app;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_redirect off;
        # set timeout
        proxy_connect_timeout   600;
        proxy_send_timeout      600;
        proxy_read_timeout      600;
        # kill cache
        add_header Last-Modified $date_gmt;
        add_header Cache-Control 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
        if_modified_since off;
        expires off;
        etag off;
    }

    location /ws/ {
        proxy_pass http://django_app;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

    client_max_body_size 1028M;
}
