# Generated by Django 6.0.3 on 2026-04-17 10:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MigrationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('data', models.JSONField(default=dict, verbose_name='Data Migration')),
                ('applied', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Data Migration',
                'verbose_name_plural': 'Data Migrations',
                'db_table': 'django_data_migrations',
                'ordering': ('-id',),
                'permissions': (),
                'default_permissions': (),
                'indexes': [models.Index(fields=['-id'], name='django_data_id_87fcc5_idx')],
            },
        ),
    ]
