# Generated by Django 6.0.3 on 2026-04-17 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_partition_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='examset',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
