# Generated by Django 6.0.3 on 2026-04-17 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_examset_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examset',
            name='is_active',
        ),
    ]
