# Generated by Django 6.0.3 on 2026-04-17 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_remove_examset_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='referenced_answer',
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='questions.comment'),
        ),
        migrations.AddField(
            model_name='comment',
            name='referenced_answers',
            field=models.ManyToManyField(blank=True, related_name='comments', to='questions.answer'),
        ),
    ]
