# Generated by Django 6.0.3 on 2026-04-18 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_remove_comment_referenced_answer_comment_parent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='examset',
            name='price_credits',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='UserExamUnlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits_spent', models.PositiveIntegerField()),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('exam_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocks', to='questions.examset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_unlocks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'questions_userexamunlock',
                'ordering': ['-unlocked_at'],
                'unique_together': {('user', 'exam_set')},
            },
        ),
    ]
